- name: restore original sudoers file
  hosts: rhel
  gather_facts: false
  become: yes

  tasks:
  
    - name: copy original sudoers to rhel vms
      copy: 
        src: ./files/sudoers
        dest: /etc/sudoers
  